version: "3.1"

services:
  civitour-database:
    container_name: civitour-database
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "civitour-db"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      default:
        aliases:
          - postgres.service
